package com.rahees.quickscan.ui.theme

import androidx.compose.ui.graphics.Color

val Teal700 = Color(0xFF00897B)
val Teal500 = Color(0xFF009688)
val Teal400 = Color(0xFF26A69A)
val Teal200 = Color(0xFF80CBC4)
val Teal50 = Color(0xFFE0F2F1)

val TealDark = Color(0xFF00695C)
val TealLight = Color(0xFF4DB6AC)

val md_theme_light_primary = Color(0xFF00897B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA7F5E7)
val md_theme_light_onPrimaryContainer = Color(0xFF002019)
val md_theme_light_secondary = Color(0xFF26A69A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCEE9E4)
val md_theme_light_onSecondaryContainer = Color(0xFF051F1A)
val md_theme_light_tertiary = Color(0xFF80CBC4)
val md_theme_light_onTertiary = Color(0xFF003731)
val md_theme_light_tertiaryContainer = Color(0xFFBDF0EA)
val md_theme_light_onTertiaryContainer = Color(0xFF002019)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFB)
val md_theme_light_onBackground = Color(0xFF191C1B)
val md_theme_light_surface = Color(0xFFFAFDFB)
val md_theme_light_onSurface = Color(0xFF191C1B)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E1)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4946)
val md_theme_light_outline = Color(0xFF6F7976)

val md_theme_dark_primary = Color(0xFF4DB6AC)
val md_theme_dark_onPrimary = Color(0xFF00382E)
val md_theme_dark_primaryContainer = Color(0xFF005045)
val md_theme_dark_onPrimaryContainer = Color(0xFFA7F5E7)
val md_theme_dark_secondary = Color(0xFF80CBC4)
val md_theme_dark_onSecondary = Color(0xFF1A3730)
val md_theme_dark_secondaryContainer = Color(0xFF304D47)
val md_theme_dark_onSecondaryContainer = Color(0xFFCEE9E4)
val md_theme_dark_tertiary = Color(0xFFA2D4CE)
val md_theme_dark_onTertiary = Color(0xFF033731)
val md_theme_dark_tertiaryContainer = Color(0xFF234E48)
val md_theme_dark_onTertiaryContainer = Color(0xFFBDF0EA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1B)
val md_theme_dark_onBackground = Color(0xFFE1E3E0)
val md_theme_dark_surface = Color(0xFF191C1B)
val md_theme_dark_onSurface = Color(0xFFE1E3E0)
val md_theme_dark_surfaceVariant = Color(0xFF3F4946)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C5)
val md_theme_dark_outline = Color(0xFF899390)
